apiVersion: "authentication.istio.io/v1alpha1"
kind: "Policy"
metadata:
  name: "jwt-keycloak"
spec:
  targets:
  - name: backend
  peers:
  - mtls: {}
  origins:
  - jwt:
      issuer: "http://192.168.99.100:30080/auth/realms/istio"
      jwksUri: "http://192.168.99.100:30080/auth/realms/istio/protocol/openid-connect/certs"
      audiences:
      - account
  principalBinding: USE_ORIGIN
